import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/ui/themes'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: dark,
        variables: {
          colorBackground: 'var(--bg-surface)',
          colorInput: 'var(--bg-subtle)',
          colorInputForeground: 'var(--text-primary)',
          colorForeground: 'var(--text-primary)',
          colorMuted: 'var(--text-secondary)',
          colorPrimary: 'var(--accent-primary)',
          colorDanger: 'var(--state-error)',
          colorSuccess: 'var(--state-success)',
          colorNeutral: 'var(--text-muted)',
          colorBorder: 'var(--border-default)',
          borderRadius: '0.75rem',
          fontFamily: 'var(--font-geist-sans)'
        },
        elements: {
          footer: {
            background: 'var(--bg-surface)',
            borderTop: '1px solid var(--border-default)',
            color: 'var(--text-faint)'
          },
          footerItem: { color: 'var(--text-faint)' },
          footerAction: {
            background: 'var(--bg-surface)',
            color: 'var(--text-faint)'
          },
          footerActionText: { color: 'var(--text-faint)' },
          footerActionLink: { color: 'var(--text-muted)' },
          footerPages: {
            background: 'var(--bg-surface)',
            color: 'var(--text-faint)'
          },
          footerPagesLink: { color: 'var(--text-faint)' },
          userButtonPopoverFooter: {
            background: 'var(--bg-elevated)',
            borderTop: '1px solid var(--border-default)',
            color: 'var(--text-faint)'
          },
          userButtonPopoverFooterPagesLink: { color: 'var(--text-faint)' },
          /* UserProfile modal */
          card: {
            background: 'var(--bg-surface)',
            boxShadow: 'none',
            border: '1px solid var(--border-default)'
          },
          navbar: {
            background: 'var(--bg-surface)',
            borderRight: '1px solid var(--border-default)'
          },
          navbarButton: { color: 'var(--text-secondary)' },
          'navbarButton:active': {
            color: 'var(--text-primary)',
            background: 'var(--bg-elevated)'
          },
          scrollBox: { background: 'var(--bg-surface)' },
          pageScrollBox: { background: 'var(--bg-base)' }
        }
      }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  )
}
